# Generated by Django 5.1.5 on 2025-03-25 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50)),
                ('received_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('fault_category', models.CharField(choices=[('MNP', 'Maintenance Non Planifiée'), ('MCP', 'Maintenance Curative Planifiée'), ('AUT', 'Travaux Divers ou Amélioration')], max_length=3)),
                ('fault_what', models.JSONField(default=list)),
                ('fault_why', models.JSONField(default=list)),
                ('fault_where', models.JSONField(default=list)),
                ('spare_parts', models.JSONField(default=list)),
                ('comments', models.TextField(blank=True)),
                ('maintenance_approval', models.CharField(blank=True, max_length=255)),
                ('production_approval', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
