# Generated by Django 5.1.5 on 2025-04-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='fault_category',
            field=models.CharField(blank=True, choices=[('MNP', 'Maintenance Non Planifiée'), ('MCP', 'Maintenance Curative Planifiée'), ('AUT', 'Travaux Divers ou Amélioration')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='fault_what',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='fault_where',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='fault_why',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='maintenance_approval',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='production_approval',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='spare_parts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='technician',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
