# Generated by Django 5.1.5 on 2025-04-01 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_intervention_comments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='maintenance_approval',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='production_approval',
        ),
        migrations.AlterField(
            model_name='intervention',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
