# Generated by Django 5.1.5 on 2025-04-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_remove_intervention_maintenance_approval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervention',
            old_name='technician',
            new_name='technicien',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='matricule',
        ),
    ]
