# Generated by Django 5.1.6 on 2025-04-27 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_machine_sparepart_intervention_machine_workorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='used_spare_parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.sparepart'),
        ),
    ]
