# Generated by Django 5.1.6 on 2025-04-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_intervention_used_spare_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='fault_what',
            field=models.CharField(blank=True, choices=[('motor', 'Motor'), ('sensor', 'Sensor'), ('belt', 'Belt'), ('pump', 'Pump'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='fault_where',
            field=models.CharField(blank=True, choices=[('line1', 'Line 1'), ('line2', 'Line 2'), ('sectionA', 'Section A'), ('sectionB', 'Section B'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='fault_why',
            field=models.CharField(blank=True, choices=[('wear', 'Wear and Tear'), ('misalignment', 'Misalignment'), ('electrical', 'Electrical Issue'), ('overload', 'Overload'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
