# Generated by Django 5.1.6 on 2025-04-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_alter_intervention_fault_what_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='machine_name',
        ),
        migrations.AddField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('in_progress', 'In Progress'), ('fixed', 'Fixed Now'), ('not_fixed', 'Not Fixed')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('in_progress', 'In Progress'), ('fixed', 'Fixed Now'), ('not_fixed', 'Not Fixed')], default='default', max_length=20),
        ),
    ]
