# Generated by Django 5.1.6 on 2025-04-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_remove_workorder_machine_name_workorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('in_progress', 'In Progress'), ('fixed', 'Fixed Now'), ('not_fixed', 'Not Fixed')], default='default', max_length=20),
        ),
    ]
